version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env
    depends_on:
      - db_test
  db_test:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A main worker -l info
    env_file:
      - .env
    depends_on:
      - db_test
      - redis
      - app
volumes:
  pgdata: