# Generated by Django 4.1.5 on 2023-01-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="category", name="date", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
